import type { Experience } from "./types";

export const experience: Experience[] = [
  {
    id: "ravn-agentic-2026",
    company: "Ravn",
    role: "Agentic Software Engineer",
    location: "United States (Remote)",
    employmentType: "Contract",
    start: "2026-01",
    end: "present",
    bullets: [
      "Building healthcare compliance SaaS and internal projects at Ravn (US remote, contract).",
      "Own architecture, implementation, tests, and production deploys for those products, using Claude and Claude Code.",
      "Apply artificial intelligence across the delivery loop so the work is specified, coded, tested, and deployed end to end.",
    ],
    tech: ["Claude Code", "Artificial Intelligence"],
  },
  {
    id: "ravn-backend-2025",
    company: "Ravn",
    role: "NodeJS Software Engineer",
    location: "United States (Remote)",
    employmentType: "Contract",
    start: "2025-07",
    end: "present",
    bullets: [
      "Building a human resources software platform with NestJS on Google Cloud Platform (US remote, contract).",
      "Shipping and maintaining the NestJS backend for that HR platform in production.",
    ],
    tech: ["Google Cloud Platform", "NestJS"],
  },
  {
    id: "banco-integral-backend-2024",
    company: "Banco Integral",
    role: "Backend Software Engineer",
    location: "San Salvador, El Salvador",
    employmentType: "Contract",
    start: "2024-11",
    end: "2025-02",
    bullets: [
      "Shipped a DTE integration project for digital tax documents at Banco Integral (San Salvador, contract).",
      "Developed and maintained backend services using NestJS and TypeScript to support critical business processes.",
      "Designed and implemented gRPC communication using proto files to enhance data exchange between microservices for DTEs.",
      "Contributed to the development of microservices architecture, improving scalability and fault tolerance.",
      "Integrated React framework Remix (Server-Side Rendering) for the frontend to consult and display all digital tax documents (DTEs).",
      "Collaborated with cross-functional teams to ensure seamless integration of backend services with frontend components.",
      "Optimized backend processes to improve system performance and reduce response times.",
      "Delivered the work in Kanban.",
    ],
    tech: ["Microservices", "Kanban", "NestJS", "TypeScript", "gRPC", "Remix", "React"],
  },
  {
    id: "muchiwa-fullstack-2023",
    company: "MUCHIWA, INC",
    role: "Full Stack Engineer",
    location: "United States (Remote)",
    employmentType: "Contract",
    start: "2023-08",
    end: "2024-04",
    bullets: [
      "Shipped DTE store, veterinary, and blood lab systems for MUCHIWA, INC (US remote, contract).",
      "Developed and maintained both frontend (Vue.js, HTML5) and backend (Node.js, MySQL) components, delivering new features and hotfixes for ERP systems for veterinary, blood laboratory, and billing.",
      "Implemented a transfer module to automate data movement between systems.",
      "Created a custom search bar for faster loading and improved performance of table components.",
      "Built a dental tracking system for caries and endodontics, enhancing user efficiency.",
      "Generated various CTE reports for clients, improving reporting accuracy.",
      "Developed barcode functionality for products and services to streamline inventory management.",
      "Managed task assignments, requirement gathering, and project deadlines while collaborating with a small team in Kanban.",
    ],
    tech: ["HTML5", "Kanban", "Vue.js", "Node.js", "MySQL"],
  },
  {
    id: "career-break-2022",
    company: "Professional development",
    role: "Career break",
    location: "Santa Ana, El Salvador",
    start: "2022-06",
    end: "2023-07",
    bullets: [
      "Took a career break in Santa Ana, El Salvador to prioritize academic studies, diving deep into mathematics and programming.",
      "Dedicated time to personal development and strategic thinking through active involvement in the chess community.",
    ],
  },
  {
    id: "moondev-fullstack-2021",
    company: "MoonDev",
    role: "Full Stack Developer",
    location: "El Salvador (Hybrid)",
    employmentType: "Contract",
    start: "2021-01",
    end: "2022-06",
    bullets: [
      "Built a transport management system at MoonDev (El Salvador, hybrid, contract).",
      "Implemented the system with Java, Spring Boot, Node.js, React.js, TypeScript, and JavaScript.",
      "Used MySQL and MongoDB for data, REST APIs for services, and OAuth with OpenID Connect (OIDC) for identity.",
    ],
    tech: [
      "MySQL",
      "TypeScript",
      "Java",
      "OAuth",
      "Spring Boot",
      "REST APIs",
      "MongoDB",
      "JavaScript",
      "OpenID Connect (OIDC)",
      "React.js",
      "Node.js",
    ],
  },
  {
    id: "digital-solutions-repair-2017",
    company: "Digit@l Solutions",
    role: "Computer Repair Technician",
    location: "El Salvador, Chalchuapa",
    employmentType: "Internship",
    start: "2017-11",
    end: "2018-01",
    bullets: [
      "Diagnosed and repaired hardware and software issues, restoring functionality to customer systems.",
      "Replaced defective hardware components and performed system upgrades to improve performance.",
      "Assisted in software installations and configurations to ensure proper functionality.",
    ],
  },
  {
    id: "ce-insa-it-2016",
    company: "CE INSA",
    role: "IT Technician",
    location: "El Salvador, Santa Ana",
    employmentType: "Internship",
    start: "2016-05",
    end: "2016-08",
    bullets: [
      "Provided technical assistance and support for computer systems and network issues.",
      "Diagnosed and resolved hardware and connectivity problems and improved security for students.",
    ],
  },
];
