import type { Experience } from "./types";

export const experience: Experience[] = [
  {
    id: "ravn-backend-2025",
    company: "RAVN",
    role: "Back End Developer",
    location: "United States (Project)",
    start: "2025-07",
    end: "present",
    bullets: [
      "Developed a complete e-commerce API using NestJS, TypeScript, and PostgreSQL with a hybrid REST/GraphQL architecture.",
      "Designed and integrated the Stripe payment gateway to facilitate seamless, secure, and PCI-compliant financial transactions for GuardianMD (USA healthcare industry).",
      "Architected and deployed scalable, serverless backend workflows utilizing AWS Lambda, optimizing system performance and reducing operational overhead.",
      "Implemented secure user authentication, authorization, and identity management flows using AWS Cognito for GuardianMD.",
      "Implemented a comprehensive authentication system (sign up, sign in, password recovery) with schema validation and global exception filters.",
      "Developed role-based functionalities (Manager/Client) with custom guards, validation pipes, and custom decorators.",
      "Created a product management system with pagination, category search, shopping cart, and product liking functionality.",
      "Managed and optimized cloud infrastructure across AWS to ensure high availability and reliability for core application services.",
      "Implemented background jobs for automatic email notifications when product stock reaches critical levels.",
      "Configured security measures, including Helmet, CORS, and rate limiting for sensitive endpoints like password reset.",
      "Applied testing methodologies (TDD, BDD, Functional Testing) using Jest with mocking and snapshot testing to ensure code quality.",
      "Developed GraphQL queries with optimized resolve fields and REST endpoints for critical authentication and payment features.",
      "Integrated an AI chatbot (with Gemini models) made in GO, communicating through gRPC to our core backend, to help make CRUD tasks for admins using the chat as an interface with the help of the AI.",
    ],
    tech: [
      "NestJS",
      "TypeScript",
      "PostgreSQL",
      "REST",
      "GraphQL",
      "Stripe",
      "AWS Lambda",
      "AWS Cognito",
      "Jest",
      "Go",
      "Gemini",
      "gRPC",
    ],
  },
  {
    id: "banco-integral-backend-2024",
    company: "Banco Integral",
    role: "Back End Developer",
    location: "El Salvador (Project)",
    start: "2024-11",
    end: "2025-02",
    bullets: [
      "Developed and maintained backend services using NestJS and TypeScript to support critical business processes.",
      "Designed and implemented gRPC communication using proto files to enhance data exchange between microservices for DTEs.",
      "Contributed to the development of microservices architecture, improving scalability and fault tolerance.",
      "Integrated React framework Remix (Server-Side Rendering) for the frontend to consult and display all digital tax documents (DTEs).",
      "Collaborated with cross-functional teams to ensure seamless integration of backend services with frontend components.",
      "Optimized backend processes to improve system performance and reduce response times.",
    ],
    tech: ["NestJS", "TypeScript", "gRPC", "Remix", "React"],
  },
  {
    id: "muchiwa-fullstack-2023",
    company: "Muchiwa",
    role: "Full Stack Developer",
    location: "El Salvador (Remote)",
    start: "2023-08",
    end: "2024-04",
    bullets: [
      "Developed and maintained both frontend (Vue.js) and backend (Node.js, MySQL) components, delivering new features and hotfixes for ERP systems for veterinary, blood laboratory, and billing.",
      "Implemented a transfer module to automate data movement between systems.",
      "Created a custom search bar for faster loading and improved performance of table components.",
      "Built a dental tracking system for caries and endodontics, enhancing user efficiency.",
      "Generated various CTE reports for clients, improving reporting accuracy.",
      "Developed barcode functionality for products and services to streamline inventory management.",
      "Managed task assignments, requirement gathering, and project deadlines while collaborating with a small team.",
    ],
    tech: ["Vue.js", "Node.js", "MySQL"],
  },
  {
    id: "moondev-fullstack-2021",
    company: "MoonDev",
    role: "Full Stack Developer",
    location: "El Salvador (Remote)",
    start: "2021-01",
    end: "2022-06",
    bullets: [
      "Maintained legacy .NET and JavaEE Servlet/JSP applications while leading a gradual migration to a modern Spring Boot and React architecture.",
      "Created new API endpoints and microservices to support additional functionality and improve data flow.",
      "Identified system inefficiencies and implemented solutions to optimize performance.",
      "Led bug fixing and technical support, ensuring stable and reliable software releases.",
      "Managed testing and deployment pipelines to ensure smooth delivery of updates.",
    ],
    tech: [".NET", "JavaEE", "Servlet/JSP", "Spring Boot", "React"],
  },
  {
    id: "digital-solutions-repair-2017",
    company: "Digit@l Solutions",
    role: "Computer Repair Technician",
    location: "El Salvador, Chalchuapa",
    employmentType: "Internship",
    start: "2017-11",
    end: "2018-01",
    bullets: [
      "Diagnosed and repaired hardware and software issues, restoring functionality to customer systems.",
      "Replaced defective hardware components and performed system upgrades to improve performance.",
      "Assisted in software installations and configurations to ensure proper functionality.",
    ],
  },
  {
    id: "ce-insa-it-2016",
    company: "CE INSA",
    role: "IT Technician",
    location: "El Salvador, Santa Ana",
    employmentType: "Internship",
    start: "2016-05",
    end: "2016-08",
    bullets: [
      "Provided technical assistance and support for computer systems and network issues.",
      "Diagnosed and resolved hardware and connectivity problems and improved security for students.",
    ],
  },
];
